Repository ironcore-dev/cluster-api-provider-ironcore-metal, pull requests merged in 2024-08, with the labels that each got.

#15 Handle Unbound ServerClaims
  internal/controller/metalmachine_controller.go
Labels: bug, size/S

#19 Allow Configuring `Image` for MetalMachines
  api/v1alpha1/metalmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachinetemplates.yaml
  config/samples/infrastructure_v1alpha1_metalmachinetemplate.yaml
  internal/controller/metalmachine_controller.go
Labels: enhancement, api-change, size/S

#22 Fix ProviderID Format for MetalMachines
  internal/controller/metalmachine_controller.go
Labels: bug, size/S

#23 Fix ProviderID
  internal/controller/metalmachine_controller.go
Labels: bug, size/XS
