Repository ironcore-dev/cluster-api-provider-ironcore-metal, pull requests merged in 2024-07, with the labels that each got.

#9 Implement ServerClaim-handling in MetalMachine Controller
  .gitignore
  api/v1alpha1/metalmachine_types.go
  cmd/main.go
  config/rbac/role.yaml
  docs/api-reference/api.md
  go.mod
  go.sum
  internal/controller/metalmachine_controller.go
Labels: documentation, enhancement, api-change, size/L

#12 Add `metal-operator` in tilt
  Tiltfile
Labels: enhancement, size/M

#13 change dev setup to use ignition in `KubeadmControlPlane`
  Tiltfile
  templates/test/cluster_v1beta1_kubeadmcontrolplane.yaml
Labels: enhancement, size/L
