Repository ironcore-dev/cluster-api-provider-ironcore-metal, pull requests merged in 2025-04, with the labels that each got.

#77 Set OwnerReference to `IPAddress`
  config/rbac/role.yaml
  internal/controller/ironcoremetalmachine_controller.go
  internal/controller/ironcoremetalmachine_controller_test.go
Labels: enhancement, size/M

#82 Update container build and publish workflow
  .github/workflows/publish-docker.yml
  REUSE.toml
  internal/controller/ironcoremetalmachine_controller.go
Labels: size/M, ok-to-image, chore

#81 Add owner reference to ipAddressClaims
  internal/controller/ironcoremetalmachine_controller.go
  internal/controller/ironcoremetalmachine_controller_test.go
Labels: size/L

#84 Refactor IP address claim labels to use separate name and namespace keys
  internal/controller/ironcoremetalmachine_controller.go
  internal/controller/ironcoremetalmachine_controller_test.go
Labels: size/S

#87 Add `cluster.clusterNetwork` to configure `APIServerPort`
  api/v1alpha1/ironcoremetalcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ironcoremetalclusters.yaml
Labels: enhancement, size/M, api-change
